name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        sdk: [stable, master]

    runs-on: ${{ matrix.os }}

    env:
      DISPLAY: :99 # For Linux x11

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.sdk }}
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
          architecture: x64 # optional, x64 or arm64

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Setup Linux x11 environment
        if: runner.os == 'Linux'
        run: sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Run tests
        working-directory: ./example
        run: flutter test integration_test
